type Query {
    categories: [Category]
}

type Category {
    id: Int
    name: String
}

type Mutation {
    createCategory(name: String): [Category],
    updateCategory(id: Int, name: String): [Category],
    deleteCategory(id: Int): [Category]
}

type Subscription {
    categories: [Category]
}
